#server:
#  port: 9010
#spring:
#  application:
#    name: iot-platform-location-server
#  profiles:
#    active: db
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8762/eureka
